/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.perfectdayforecast.app

import com.example.perfecdayforecast.collector.Location
import com.example.perfectdayforecast.collector.handlers.WeatherForecastApiHandler
import java.time.LocalDate

fun main() {
    println("Hello from Data Collector")
    val baseUrl = "https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&daily=weathercode,temperature_2m_max,temperature_2m_min,rain_sum,snowfall_sum,precipitation_sum,precipitation_probability_max&timezone=auto&start_date={start_date}&end_date={end_date}"
    val handler = WeatherForecastApiHandler(baseUrl)
    val result = handler.getData(Location.TOKYO, LocalDate.of(2023, 10, 8), LocalDate.of(2023, 10, 10))

    print(result.toString())
}
