/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package com.example.perfectdayforecast.list

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.*

class AnalyzerTest {
    @Test
    fun testConstructor() {

    }

}
